// AUTO-GENERATED by scripts/extract-jsonl-schema.ts — do not edit by hand.
export type Uuid = string;
export type Sha1 = string;
export type Semver = string;
export type IsoDate = string;
export type Url = string;
export type Path = string;
export type Blob = string;

/** session_meta */
export type SessionMeta_e98689a8 = {
  payload: {
    base_instructions: {
      text: Path;
    };
    cli_version: Semver;
    cwd: Path;
    git: {
      branch: string;
      commit_hash: Sha1;
      repository_url: Url;
    };
    id: Uuid;
    model_provider: string;
    originator: string;
    source: string;
    timestamp: IsoDate;
  };
  timestamp: IsoDate;
  type: "session_meta";
};

/** event_msg.payload -> task_started */
export type Payload_TaskStarted_b07888eb = {
  collaboration_mode_kind: string;
  model_context_window: number;
  started_at: number;
  turn_id: Uuid;
  type: "task_started";
};

/** event_msg.payload -> user_message */
export type Payload_UserMessage_1024ed31 = {
  images: never[];
  local_images: never[];
  message: string;
  text_elements: never[];
  type: "user_message";
};

/** event_msg.payload -> token_count.info -> Variant */
export type Info_Variant_b8550efc = {
  last_token_usage: {
    cached_input_tokens: number;
    input_tokens: number;
    output_tokens: number;
    reasoning_output_tokens: number;
    total_tokens: number;
  };
  model_context_window: number;
  total_token_usage: {
    cached_input_tokens: number;
    input_tokens: number;
    output_tokens: number;
    reasoning_output_tokens: number;
    total_tokens: number;
  };
};

/** event_msg.payload -> token_count */
export type Payload_TokenCount_ed9cbd7e = {
  info: null | Info_Variant_b8550efc;
  rate_limits: {
    credits: {
      balance: null;
      has_credits: boolean;
      unlimited: boolean;
    };
    limit_id: string;
    limit_name: null;
    plan_type: null;
    primary: {
      resets_at: number;
      used_percent: number;
      window_minutes: number;
    };
    rate_limit_reached_type: null;
    secondary: {
      resets_at: number;
      used_percent: number;
      window_minutes: number;
    };
  };
  type: "token_count";
};

/** event_msg.payload -> agent_message */
export type Payload_AgentMessage_60d7ed19 = {
  memory_citation: null;
  message: Blob;
  phase: string;
  type: "agent_message";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> list_files */
export type ParsedCmd_ListFiles_7775f28f = {
  cmd: string;
  path: string;
  type: "list_files";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> search */
export type ParsedCmd_Search_09476b88 = {
  cmd: string;
  path: string;
  query: string;
  type: "search";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> read */
export type ParsedCmd_Read_2f1ac1fc = {
  cmd: string;
  name: string;
  path: string;
  type: "read";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> unknown */
export type ParsedCmd_Unknown_0d6c552b = {
  cmd: string;
  type: "unknown";
};

/** event_msg.payload -> exec_command_end */
export type Payload_ExecCommandEnd_ce7217dd = {
  aggregated_output: string;
  call_id: string;
  command: string[];
  cwd: Path;
  duration: {
    nanos: number;
    secs: number;
  };
  exit_code: number;
  formatted_output: string;
  parsed_cmd: Array<ParsedCmd_ListFiles_7775f28f | ParsedCmd_Search_09476b88 | ParsedCmd_Read_2f1ac1fc | ParsedCmd_Unknown_0d6c552b>;
  process_id: string;
  source: string;
  status: string;
  stderr: string;
  stdout: string;
  turn_id: Uuid;
  type: "exec_command_end";
};

/** event_msg.payload -> patch_apply_end.changes{} -> update */
export type Changes_Update_f8d54454 = {
  move_path: null;
  type: "update";
  unified_diff: string;
};

/** event_msg.payload -> patch_apply_end.changes{} -> add */
export type Changes_Add_1802d286 = {
  content: Blob;
  type: "add";
};

/** event_msg.payload -> patch_apply_end */
export type Payload_PatchApplyEnd_2042383b = {
  call_id: string;
  changes: Record<Path, Changes_Update_f8d54454 | Changes_Add_1802d286>;
  status: string;
  stderr: string;
  stdout: Path;
  success: boolean;
  turn_id: Uuid;
  type: "patch_apply_end";
};

/** event_msg.payload -> task_complete */
export type Payload_TaskComplete_4f8df77f = {
  completed_at: number;
  duration_ms: number;
  last_agent_message: Blob | null;
  time_to_first_token_ms: number;
  turn_id: Uuid;
  type: "task_complete";
};

/** event_msg.payload -> turn_aborted */
export type Payload_TurnAborted_9f451e06 = {
  completed_at: number;
  duration_ms: number;
  reason: string;
  turn_id: Uuid;
  type: "turn_aborted";
};

/** event_msg.payload -> item_completed */
export type Payload_ItemCompleted_b2a6746d = {
  item: {
    id: string;
    text: Path;
    type: "Plan";
  };
  thread_id: Uuid;
  turn_id: Uuid;
  type: "item_completed";
};

/** event_msg */
export type EventMsg_0bc1a1a1 = {
  payload: Payload_TaskStarted_b07888eb | Payload_UserMessage_1024ed31 | Payload_TokenCount_ed9cbd7e | Payload_AgentMessage_60d7ed19 | Payload_ExecCommandEnd_ce7217dd | Payload_PatchApplyEnd_2042383b | Payload_TaskComplete_4f8df77f | Payload_TurnAborted_9f451e06 | Payload_ItemCompleted_b2a6746d;
  timestamp: IsoDate;
  type: "event_msg";
};

/** response_item.payload -> message */
export type Payload_Message_81e18e21 = {
  content: {
    text: string;
    type: "input_text";
  }[];
  role: "developer" | "user";
  type: "message";
};

/** response_item.payload -> reasoning */
export type Payload_Reasoning_82ea41c5 = {
  content: null;
  encrypted_content: Blob;
  summary: never[];
  type: "reasoning";
};

/** response_item.payload -> message */
export type Payload_Message_81e18e21_2 = {
  content: {
    text: Blob;
    type: "output_text";
  }[];
  phase: string;
  role: "assistant";
  type: "message";
};

/** response_item.payload -> function_call */
export type Payload_FunctionCall_2fb2ebf2 = {
  arguments: Blob;
  call_id: string;
  name: string;
  type: "function_call";
};

/** response_item.payload -> function_call_output */
export type Payload_FunctionCallOutput_ee54e611 = {
  call_id: string;
  output: Blob;
  type: "function_call_output";
};

/** response_item.payload -> custom_tool_call */
export type Payload_CustomToolCall_fd33fb92 = {
  call_id: string;
  input: Path;
  name: string;
  status: string;
  type: "custom_tool_call";
};

/** response_item.payload -> custom_tool_call_output */
export type Payload_CustomToolCallOutput_e3c1bb6b = {
  call_id: string;
  output: Path;
  type: "custom_tool_call_output";
};

/** response_item */
export type ResponseItem_0218eace = {
  payload: Payload_Message_81e18e21 | Payload_Reasoning_82ea41c5 | Payload_Message_81e18e21_2 | Payload_FunctionCall_2fb2ebf2 | Payload_FunctionCallOutput_ee54e611 | Payload_CustomToolCall_fd33fb92 | Payload_CustomToolCallOutput_e3c1bb6b;
  timestamp: IsoDate;
  type: "response_item";
};

/**
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> path
 * turn_context.payload.permission_profile.file_system.entries[].path -> path
 */
export type Path_Path_7618260e = {
  path: Path;
  type: "path";
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> root
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> root
 */
export type Value_Root_73bc7478 = {
  kind: "root";
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> project_roots
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> project_roots
 */
export type Value_ProjectRoots_7012ad95 = {
  kind: "project_roots";
  subpath?: string;
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> slash_tmp
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> slash_tmp
 */
export type Value_SlashTmp_113ccc33 = {
  kind: "slash_tmp";
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> tmpdir
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> tmpdir
 */
export type Value_Tmpdir_1e713077 = {
  kind: "tmpdir";
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> special
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special
 */
export type Path_Special_103b9549 = {
  type: "special";
  value: Value_Root_73bc7478 | Value_ProjectRoots_7012ad95 | Value_SlashTmp_113ccc33 | Value_Tmpdir_1e713077;
};

/** turn_context */
export type TurnContext_d55c4b58 = {
  payload: {
    approval_policy: string;
    collaboration_mode: {
      mode: string;
      settings: {
        developer_instructions: Path;
        model: string;
        reasoning_effort: string;
      };
    };
    current_date: IsoDate;
    cwd: Path;
    effort: string;
    file_system_sandbox_policy: {
      entries: {
        access: string;
        path: Path_Special_103b9549 | Path_Path_7618260e;
      }[];
      kind: "restricted";
    };
    model: string;
    permission_profile: {
      file_system: {
        entries: {
          access: string;
          path: Path_Special_103b9549 | Path_Path_7618260e;
        }[];
        type: "restricted";
      };
      network: string;
      type: "managed";
    };
    personality: string;
    realtime_active: boolean;
    sandbox_policy: {
      exclude_slash_tmp: boolean;
      exclude_tmpdir_env_var: boolean;
      network_access: boolean;
      type: "workspace-write";
      writable_roots: Path[];
    };
    summary: string;
    timezone: Path;
    truncation_policy: {
      limit: number;
      mode: string;
    };
    turn_id: Uuid;
  };
  timestamp: IsoDate;
  type: "turn_context";
};

export type Root = SessionMeta_e98689a8 | EventMsg_0bc1a1a1 | ResponseItem_0218eace | TurnContext_d55c4b58;
