// AUTO-GENERATED by scripts/extract-jsonl-schema.ts — do not edit by hand.
export type Uuid = string;
export type Sha1 = string;
export type Semver = string;
export type IsoDate = string;
export type Url = string;
export type Path = string;
export type Blob = string;

/** session_meta */
export type SessionMeta_d46e830c = {
  payload: {
    base_instructions: {
      text: Path;
    };
    cli_version: Semver;
    cwd: Path;
    git: {
      branch: string;
      commit_hash: Sha1;
      repository_url: Url;
    };
    id: Uuid;
    model_provider: string;
    originator: string;
    source: string;
    timestamp: IsoDate;
  };
  timestamp: IsoDate;
  type: "session_meta";
};

/** event_msg.payload -> task_started */
export type Payload_TaskStarted_45880111 = {
  collaboration_mode_kind: string;
  model_context_window: number;
  started_at: number;
  turn_id: Uuid;
  type: "task_started";
};

/** event_msg.payload -> user_message */
export type Payload_UserMessage_199e6c69 = {
  images: never[];
  local_images: never[];
  message: string;
  text_elements: never[];
  type: "user_message";
};

/** event_msg.payload -> token_count.info -> Variant */
export type Info_Variant_ca24c77d = {
  last_token_usage: {
    cached_input_tokens: number;
    input_tokens: number;
    output_tokens: number;
    reasoning_output_tokens: number;
    total_tokens: number;
  };
  model_context_window: number;
  total_token_usage: {
    cached_input_tokens: number;
    input_tokens: number;
    output_tokens: number;
    reasoning_output_tokens: number;
    total_tokens: number;
  };
};

/** event_msg.payload -> token_count */
export type Payload_TokenCount_3307a0d0 = {
  info: null | Info_Variant_ca24c77d;
  rate_limits: {
    credits: {
      balance: null;
      has_credits: boolean;
      unlimited: boolean;
    };
    limit_id: string;
    limit_name: null;
    plan_type: null;
    primary: {
      resets_at: number;
      used_percent: number;
      window_minutes: number;
    };
    rate_limit_reached_type: null;
    secondary: {
      resets_at: number;
      used_percent: number;
      window_minutes: number;
    };
  };
  type: "token_count";
};

/** event_msg.payload -> agent_message */
export type Payload_AgentMessage_6e19ddd2 = {
  memory_citation: null;
  message: Blob;
  phase: string;
  type: "agent_message";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> list_files */
export type ParsedCmd_ListFiles_62acb15a = {
  cmd: string;
  path: string;
  type: "list_files";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> search */
export type ParsedCmd_Search_6ea11871 = {
  cmd: string;
  path: string;
  query: string;
  type: "search";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> read */
export type ParsedCmd_Read_62984596 = {
  cmd: string;
  name: string;
  path: string;
  type: "read";
};

/** event_msg.payload -> exec_command_end.parsed_cmd[] -> unknown */
export type ParsedCmd_Unknown_5f6eaed3 = {
  cmd: string;
  type: "unknown";
};

/** event_msg.payload -> exec_command_end */
export type Payload_ExecCommandEnd_80f61ef9 = {
  aggregated_output: string;
  call_id: string;
  command: string[];
  cwd: Path;
  duration: {
    nanos: number;
    secs: number;
  };
  exit_code: number;
  formatted_output: string;
  parsed_cmd: Array<ParsedCmd_ListFiles_62acb15a | ParsedCmd_Search_6ea11871 | ParsedCmd_Read_62984596 | ParsedCmd_Unknown_5f6eaed3>;
  process_id: string;
  source: string;
  status: string;
  stderr: string;
  stdout: string;
  turn_id: Uuid;
  type: "exec_command_end";
};

/** event_msg.payload -> patch_apply_end.changes{} -> update */
export type Changes_Update_2f313ccf = {
  move_path: null;
  type: "update";
  unified_diff: string;
};

/** event_msg.payload -> patch_apply_end.changes{} -> add */
export type Changes_Add_43e127d8 = {
  content: Blob;
  type: "add";
};

/** event_msg.payload -> patch_apply_end */
export type Payload_PatchApplyEnd_27bdf4c7 = {
  call_id: string;
  changes: Record<Path, Changes_Update_2f313ccf | Changes_Add_43e127d8>;
  status: string;
  stderr: string;
  stdout: Path;
  success: boolean;
  turn_id: Uuid;
  type: "patch_apply_end";
};

/** event_msg.payload -> task_complete */
export type Payload_TaskComplete_845a0bc8 = {
  completed_at: number;
  duration_ms: number;
  last_agent_message: Blob | null;
  time_to_first_token_ms: number;
  turn_id: Uuid;
  type: "task_complete";
};

/** event_msg.payload -> turn_aborted */
export type Payload_TurnAborted_a558d1c1 = {
  completed_at: number;
  duration_ms: number;
  reason: string;
  turn_id: Uuid;
  type: "turn_aborted";
};

/** event_msg.payload -> item_completed */
export type Payload_ItemCompleted_46c96b41 = {
  item: {
    id: string;
    text: Path;
    type: "Plan";
  };
  thread_id: Uuid;
  turn_id: Uuid;
  type: "item_completed";
};

/** event_msg */
export type EventMsg_1de87ddc = {
  payload: Payload_TaskStarted_45880111 | Payload_UserMessage_199e6c69 | Payload_TokenCount_3307a0d0 | Payload_AgentMessage_6e19ddd2 | Payload_ExecCommandEnd_80f61ef9 | Payload_PatchApplyEnd_27bdf4c7 | Payload_TaskComplete_845a0bc8 | Payload_TurnAborted_a558d1c1 | Payload_ItemCompleted_46c96b41;
  timestamp: IsoDate;
  type: "event_msg";
};

/** response_item.payload -> message */
export type Payload_Message_cdc77562 = {
  content: {
    text: string;
    type: "input_text";
  }[];
  role: "developer" | "user";
  type: "message";
};

/** response_item.payload -> reasoning */
export type Payload_Reasoning_af56dde1 = {
  content: null;
  encrypted_content: Blob;
  summary: never[];
  type: "reasoning";
};

/** response_item.payload -> message */
export type Payload_Message_cdc77562_2 = {
  content: {
    text: Blob;
    type: "output_text";
  }[];
  phase: string;
  role: "assistant";
  type: "message";
};

/** response_item.payload -> function_call */
export type Payload_FunctionCall_177cb5dd = {
  arguments: Blob;
  call_id: string;
  name: string;
  type: "function_call";
};

/** response_item.payload -> function_call_output */
export type Payload_FunctionCallOutput_030f1d78 = {
  call_id: string;
  output: Blob;
  type: "function_call_output";
};

/** response_item.payload -> custom_tool_call */
export type Payload_CustomToolCall_499c3152 = {
  call_id: string;
  input: Path;
  name: string;
  status: string;
  type: "custom_tool_call";
};

/** response_item.payload -> custom_tool_call_output */
export type Payload_CustomToolCallOutput_44a1c09b = {
  call_id: string;
  output: Path;
  type: "custom_tool_call_output";
};

/** response_item */
export type ResponseItem_dabbd39e = {
  payload: Payload_Message_cdc77562 | Payload_Reasoning_af56dde1 | Payload_Message_cdc77562_2 | Payload_FunctionCall_177cb5dd | Payload_FunctionCallOutput_030f1d78 | Payload_CustomToolCall_499c3152 | Payload_CustomToolCallOutput_44a1c09b;
  timestamp: IsoDate;
  type: "response_item";
};

/**
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> root
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> root
 */
export type Value_Root_79526242 = {
  kind: "root";
};

/**
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> project_roots
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> project_roots
 */
export type Value_ProjectRoots_3138f058 = {
  kind: "project_roots";
  subpath?: string;
};

/**
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> tmpdir
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> tmpdir
 */
export type Value_Tmpdir_1573cb88 = {
  kind: "tmpdir";
};

/**
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special
 * turn_context.payload.permission_profile.file_system.entries[].path -> special
 */
export type Path_Special_b5394781 = {
  type: "special";
  value: Value_Root_79526242 | Value_ProjectRoots_3138f058 | Value_SlashTmp_cc501f19 | Value_Tmpdir_1573cb88;
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> special.value -> slash_tmp
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> special.value -> slash_tmp
 */
export type Value_SlashTmp_cc501f19 = {
  kind: "slash_tmp";
};

/**
 * turn_context.payload.permission_profile.file_system.entries[].path -> path
 * turn_context.payload.file_system_sandbox_policy.entries[].path -> path
 */
export type Path_Path_0ba5161d = {
  path: Path;
  type: "path";
};

/** turn_context */
export type TurnContext_6ab315d9 = {
  payload: {
    approval_policy: string;
    collaboration_mode: {
      mode: string;
      settings: {
        developer_instructions: Path;
        model: string;
        reasoning_effort: string;
      };
    };
    current_date: IsoDate;
    cwd: Path;
    effort: string;
    file_system_sandbox_policy: {
      entries: {
        access: string;
        path: Path_Special_b5394781 | Path_Path_0ba5161d;
      }[];
      kind: "restricted";
    };
    model: string;
    permission_profile: {
      file_system: {
        entries: {
          access: string;
          path: Path_Special_b5394781 | Path_Path_0ba5161d;
        }[];
        type: "restricted";
      };
      network: string;
      type: "managed";
    };
    personality: string;
    realtime_active: boolean;
    sandbox_policy: {
      exclude_slash_tmp: boolean;
      exclude_tmpdir_env_var: boolean;
      network_access: boolean;
      type: "workspace-write";
      writable_roots: Path[];
    };
    summary: string;
    timezone: Path;
    truncation_policy: {
      limit: number;
      mode: string;
    };
    turn_id: Uuid;
  };
  timestamp: IsoDate;
  type: "turn_context";
};

export type Codex = SessionMeta_d46e830c | EventMsg_1de87ddc | ResponseItem_dabbd39e | TurnContext_6ab315d9;
