// AUTO-GENERATED by scripts/extract-jsonl-schema.ts — do not edit by hand.
export type VscodeCallId = string;
export type Uuid = string;
export type Semver = string;
export type Url = string;
export type Path = string;
export type Blob = string;

/** 0.v.inputState.selectedModel.metadata.extension -> Variant */
export type ExtensionId_Type_5b6f8a91 = {
  _lower: string;
  value: string;
};

/** 0.v.requests[].message.parts[] -> text */
export type Parts_Text_587c1dc1 = {
  editorRange: {
    endColumn: number;
    endLineNumber: number;
    startColumn: number;
    startLineNumber: number;
  };
  kind: "text";
  range: {
    endExclusive: number;
    start: number;
  };
  text: Path;
};

/** 0.v.requests[].modeInfo -> agent */
export type ModeInfo_Agent_b665cdab = {
  isBuiltin: boolean;
  kind: "agent";
  modeId: string;
  modeName: string;
  permissionLevel: string;
};

/**
 * 0.v.requests[].response[] -> mcpServersStarting
 * 2.v[] -> Variant.response[] -> mcpServersStarting
 */
export type Response_McpServersStarting_083d2bc5 = {
  didStartServerIds: never[];
  kind: "mcpServersStarting";
};

/** 0.v.requests[].response[] -> progressTaskSerialized */
export type Response_ProgressTaskSerialized_f7bc608c = {
  content: {
    uris: Record<string, unknown>;
    value: string;
  };
  kind: "progressTaskSerialized";
  progress: never[];
};

/** 0.v.requests[].response[] -> thinking.metadata -> Variant */
export type Metadata_Type_8ea244cb = {
  stopReason: string;
  vscodeReasoningDone: boolean;
};

/** 0.v.requests[].response[] -> thinking */
export type Response_Thinking_8de6614a = {
  id: string;
  kind: "thinking";
  metadata?: Metadata_Type_8ea244cb;
  value: never[] | string;
};

/** 0.v.requests[].response[] -> Variant.baseUri -> 1 */
export type BaseUri_1_6148a1b9 = {
  $mid: 1;
  _sep?: number;
  authority: string;
  external?: Url;
  fsPath?: Path;
  path: Path;
  scheme: string;
};

/** 0.v.requests[].response[] -> Variant */
export type Response_Variant_b9ca791d = {
  baseUri: BaseUri_1_6148a1b9;
  supportHtml: boolean;
  supportThemeIcons: boolean;
  value: string;
};

/** 0.v.requests[].response[] -> inlineReference */
export type Response_InlineReference_bb5730f5 = {
  inlineReference: BaseUri_1_6148a1b9;
  kind: "inlineReference";
};

/** 0.v.requests[].response[] -> toolInvocationSerialized.invocationMessage -> Variant */
export type InvocationMessage_Type_d84d1caa = {
  supportAlertSyntax: boolean;
  supportHtml: boolean;
  supportThemeIcons: boolean;
  uris: Record<Url, BaseUri_1_6148a1b9>;
  value: Path;
};

/** 0.v.requests[].response[] -> toolInvocationSerialized.source -> internal */
export type Source_Internal_cd45aa03 = {
  label: string;
  type: "internal";
};

/** 0.v.requests[].response[] -> toolInvocationSerialized */
export type Response_ToolInvocationSerialized_9634f614 = {
  invocationMessage: InvocationMessage_Type_d84d1caa;
  isComplete: boolean;
  isConfirmed: {
    type: 1;
  };
  kind: "toolInvocationSerialized";
  pastTenseMessage: InvocationMessage_Type_d84d1caa;
  source: Source_Internal_cd45aa03;
  toolCallId: string;
  toolId: string;
};

/** 0 */
export type $0_801eaa31 = {
  kind: 0;
  v: {
    creationDate: number;
    customTitle: string;
    hasPendingEdits: boolean;
    initialLocation: string;
    inputState: {
      attachments: never[];
      contrib: {
        chatDynamicVariableModel: never[];
      };
      inputText: string;
      mode: {
        id: string;
        kind: "agent";
      };
      permissionLevel: string;
      selectedModel: {
        identifier: Path;
        metadata: {
          auth: {
            accountLabel: string;
            providerLabel: string;
          };
          capabilities: {
            agentMode: boolean;
            toolCalling: boolean;
            vision: boolean;
          };
          configurationSchema: {
            properties: {
              reasoningEffort: {
                default: string;
                enum: string[];
                enumDescriptions: string[];
                enumItemLabels: string[];
                group: string;
                title: string;
                type: "string";
              };
            };
          };
          extension: ExtensionId_Type_5b6f8a91;
          family: string;
          id: string;
          isDefaultForLocation: {
            editor: boolean;
            notebook: boolean;
            panel: boolean;
            terminal: boolean;
          };
          isUserSelectable: boolean;
          maxInputTokens: number;
          maxOutputTokens: number;
          modelPickerCategory: {
            label: string;
            order: number;
          };
          multiplier: string;
          multiplierNumeric: number;
          name: string;
          tooltip: Blob;
          vendor: string;
          version: string;
        };
      };
      selections: {
        endColumn: number;
        endLineNumber: number;
        positionColumn: number;
        positionLineNumber: number;
        selectionStartColumn: number;
        selectionStartLineNumber: number;
        startColumn: number;
        startLineNumber: number;
      }[];
    };
    pendingRequests: never[];
    requests: {
      agent: {
        description: string;
        disambiguation: never[];
        extensionDisplayName: string;
        extensionId: ExtensionId_Type_5b6f8a91;
        extensionPublisherId: string;
        extensionVersion: Semver;
        fullName: string;
        id: string;
        isDefault: boolean;
        locations: string[];
        metadata: {
          hasFollowups: boolean;
          supportIssueReporting: boolean;
          themeIcon: {
            id: string;
          };
        };
        modes: string[];
        name: string;
        publisherDisplayName: string;
        slashCommands: {
          description: string;
          disambiguation?: {
            category: string;
            description: string;
            examples: string[];
          }[];
          isSticky?: boolean;
          name: string;
          sampleRequest?: string;
          when?: string;
        }[];
        when: string;
      };
      codeCitations: never[];
      completionTokens: number;
      contentReferences: never[];
      message: {
        parts: Parts_Text_587c1dc1[];
        text: Path;
      };
      modeInfo: ModeInfo_Agent_b665cdab;
      modelId: Path;
      modelState: {
        value: number;
      };
      requestId: string;
      response: Array<Response_McpServersStarting_083d2bc5 | Response_ProgressTaskSerialized_f7bc608c | Response_Thinking_8de6614a | Response_Variant_b9ca791d | Response_InlineReference_bb5730f5 | Response_ToolInvocationSerialized_9634f614>;
      responseId: string;
      timeSpentWaiting: number;
      timestamp: number;
      variableData: {
        variables: never[];
      };
    }[];
    responderUsername: string;
    sessionId: Uuid;
    version: number;
  };
};

/** 1.v -> Variant.metadata.renderedGlobalContext[] -> 1 */
export type RenderedGlobalContext_1_4db04af6 = {
  text: Path;
  type: 1;
};

/** 1.v -> Variant.metadata.renderedGlobalContext[] -> 3 */
export type RenderedGlobalContext_3_47ad5dfc = {
  cacheType: string;
  type: 3;
};

/** 1.v -> Variant.metadata.renderedUserMessage[] -> 1 */
export type RenderedUserMessage_1_dfe56f8a = {
  text: Path;
  type: 1;
};

/** 1.v -> Variant.metadata.renderedUserMessage[] -> 3 */
export type RenderedUserMessage_3_213f486e = {
  cacheType: string;
  type: 3;
};

/**
 * 1.v -> Variant.metadata.toolCallResults{}.content[] -> 23.value.node.children[] -> 2
 * 1.v -> Variant.metadata.toolCallResults{}.content[] -> 23.value.node.children[] -> 1.children[] -> 2
 */
export type Children_2_55534c6b = {
  lineBreakBefore: boolean;
  priority: number;
  references?: {
    anchor: BaseUri_1_6148a1b9;
    options: {
      isFromTool: boolean;
    };
  }[];
  text: string;
  type: 2;
};

/** 1.v -> Variant.metadata.toolCallResults{}.content[] -> 23.value.node.children[] -> 1 */
export type Children_1_28ac79e0 = {
  children: Array<Children_1_28ac79e0 | Children_2_55534c6b>;
  ctor: number;
  ctorName: string;
  keepWithId?: number;
  props: {
    flexGrow?: number;
    priority?: number;
  };
  references: never[];
  type: 1;
};

/** 1.v -> Variant.metadata.toolCallResults{}.content[] -> 23 */
export type Content_23_03e0de07 = {
  $mid: 23;
  value: {
    node: {
      children: Array<Children_2_55534c6b | Children_1_28ac79e0>;
      ctor: number;
      ctorName: string;
      props: Record<string, unknown>;
      references: never[];
      type: 1;
    };
  };
};

/** 1.v -> Variant.metadata.toolCallResults{}.content[] -> 21 */
export type Content_21_2696179f = {
  $mid: 21;
  value: Blob;
};

/** 1.v -> Variant */
export type V_Variant_9dcab11c = {
  completedAt?: number;
  details?: string;
  metadata?: {
    agentId: string;
    cacheKey?: Url;
    codeBlocks: never[];
    modelMessageId: Uuid;
    renderedGlobalContext?: Array<RenderedGlobalContext_1_4db04af6 | RenderedGlobalContext_3_47ad5dfc>;
    renderedUserMessage: Array<RenderedUserMessage_1_dfe56f8a | RenderedUserMessage_3_213f486e>;
    resolvedModel: string;
    responseId: Uuid;
    sessionId: Uuid;
    toolCallResults: Record<VscodeCallId, {
      $mid: 20;
      content: Array<Content_23_03e0de07 | Content_21_2696179f>;
    }>;
    toolCallRounds: {
      id: Uuid;
      phase: string;
      phaseModelId: string;
      response: Blob;
      statefulMarker: Path;
      thinking: {
        encrypted: Path;
        id: Path;
        text: never[] | Blob;
        tokens: number;
      };
      timestamp: number;
      toolCalls: {
        arguments: Path;
        id: VscodeCallId;
        name: string;
      }[];
      toolInputRetry: number;
    }[];
  };
  timings?: {
    firstProgress: number;
    totalElapsed: number;
  };
  value?: number;
};

/** 1 */
export type $1_a2c6e3e4 = {
  k: Array<string | number>;
  kind: 1;
  v: V_Variant_9dcab11c | never[] | string | number | boolean;
};

/** 2.v[] -> Variant */
export type V_Variant_ca258acf = {
  baseUri?: BaseUri_1_6148a1b9;
  done?: boolean;
  edits?: {
    range: {
      endColumn: number;
      endLineNumber: number;
      startColumn: number;
      startLineNumber: number;
    };
    text: Path;
  }[][];
  generatedTitle?: string;
  id?: string;
  invocationMessage?: InvocationMessage_Type_d84d1caa | string;
  isComplete?: boolean;
  isConfirmed?: {
    type: 1;
  };
  isEdit?: boolean;
  kind?: "codeblockUri" | "textEditGroup" | "thinking" | "toolInvocationSerialized" | "undoStop";
  metadata?: Metadata_Type_8ea244cb;
  pastTenseMessage?: InvocationMessage_Type_d84d1caa;
  presentation?: string;
  resultDetails?: never[];
  source?: Source_Internal_cd45aa03;
  supportAlertSyntax?: boolean;
  supportHtml?: boolean;
  supportThemeIcons?: boolean;
  toolCallId?: string;
  toolId?: string;
  uri?: BaseUri_1_6148a1b9;
  uris?: Record<string, unknown>;
  value?: string;
};

/** 2.v[] -> thinking */
export type V_Thinking_0d8c201c = {
  generatedTitle?: string;
  id: string;
  kind: "thinking";
  metadata?: Metadata_Type_8ea244cb;
  value: never[] | string;
};

/** 2.v[] -> Variant.response[] -> toolInvocationSerialized */
export type Response_ToolInvocationSerialized_f9d74c88 = {
  invocationMessage: InvocationMessage_Type_d84d1caa;
  isComplete: boolean;
  isConfirmed: {
    type: 1;
  };
  kind: "toolInvocationSerialized";
  pastTenseMessage: InvocationMessage_Type_d84d1caa;
  resultDetails: never[];
  source: Source_Internal_cd45aa03;
  toolCallId: Uuid;
  toolId: string;
};

/** 2.v[] -> Variant */
export type V_Variant_ca258acf_2 = {
  agent?: {
    description: string;
    disambiguation: never[];
    extensionDisplayName: string;
    extensionId: ExtensionId_Type_5b6f8a91;
    extensionPublisherId: string;
    extensionVersion: Semver;
    fullName: string;
    id: string;
    isDefault: boolean;
    locations: string[];
    metadata: {
      hasFollowups: boolean;
      supportIssueReporting: boolean;
      themeIcon: {
        id: string;
      };
    };
    modes: string[];
    name: string;
    publisherDisplayName: string;
    slashCommands: {
      description: string;
      disambiguation?: {
        category: string;
        description: string;
        examples: string[];
      }[];
      isSticky?: boolean;
      name: string;
      sampleRequest?: string;
      when?: string;
    }[];
    when: string;
  };
  baseUri?: BaseUri_1_6148a1b9;
  codeCitations?: never[];
  contentReferences?: never[];
  message?: {
    parts: Parts_Text_587c1dc1[];
    text: string;
  };
  modeInfo?: ModeInfo_Agent_b665cdab;
  modelId?: Path;
  modelState?: {
    value: number;
  };
  requestId?: string;
  response?: Array<Response_McpServersStarting_083d2bc5 | Response_ToolInvocationSerialized_f9d74c88>;
  responseId?: string;
  supportAlertSyntax?: boolean;
  supportHtml?: boolean;
  supportThemeIcons?: boolean;
  timeSpentWaiting?: number;
  timestamp?: number;
  uris?: Record<string, unknown>;
  value?: string;
  variableData?: {
    variables: {
      fullName: string;
      icon: {
        id: string;
      };
      id: string;
      kind: "tool";
      name: string;
    }[];
  };
};

/** 2.v[] -> inlineReference */
export type V_InlineReference_3f1ce092 = {
  inlineReference: BaseUri_1_6148a1b9;
  kind: "inlineReference";
  name?: string;
};

/** 2 */
export type $2_3da03859 = {
  i?: number;
  k: Array<string | number>;
  kind: 2;
  v: Array<V_Variant_ca258acf | V_Thinking_0d8c201c | V_Variant_ca258acf_2 | V_InlineReference_3f1ce092>;
};

export type CopilotChat = $0_801eaa31 | $1_a2c6e3e4 | $2_3da03859;
