// AUTO-GENERATED by scripts/extract-jsonl-schema.ts — do not edit by hand.
export type VscodeCallId = string;
export type Uuid = string;
export type Sha1 = string;
export type Semver = string;
export type Url = string;
export type Path = string;
export type Base64 = string;
export type Blob = string;

/** 0.v.inputState.attachments[].value -> 1 */
export type $mid_1_9b4a5f71 = {
  $mid: 1;
  _sep?: number;
  authority?: string;
  external?: Path;
  fragment?: string;
  fsPath?: Path;
  path: Path;
  query?: string;
  scheme: string;
};

/** 0.v.inputState.attachments[].value -> Variant.range -> Variant */
export type Range_Type_c56f3a3b = {
  endColumn: number;
  endLineNumber: number;
  startColumn: number;
  startLineNumber: number;
};

/** 0.v.inputState.attachments[].value -> Variant */
export type ResultDetails_Type_5cbf55b8 = {
  range: Range_Type_c56f3a3b;
  uri: $mid_1_9b4a5f71;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant.auth -> Variant */
export type Auth_Type_0db0f468 = {
  accountLabel: string;
  providerLabel: string;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant.capabilities -> Variant */
export type Capabilities_Type_024bea5e = {
  agentMode: boolean;
  toolCalling: boolean;
  vision: boolean;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant.extension -> Variant */
export type ExtensionId_Type_5b6f8a91 = {
  _lower: string;
  value: string;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant.isDefaultForLocation -> Variant */
export type IsDefaultForLocation_Type_b17d32ba = {
  editor: boolean;
  notebook: boolean;
  panel: boolean;
  terminal: boolean;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant.modelPickerCategory -> Variant */
export type ModelPickerCategory_Type_e766cacf = {
  label: string;
  order: number;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant */
export type Metadata_Variant_7403ebc8 = {
  auth: Auth_Type_0db0f468;
  capabilities: Capabilities_Type_024bea5e;
  configurationSchema: {
    properties: {
      reasoningEffort: {
        default: string;
        enum: string[];
        enumDescriptions: string[];
        enumItemLabels: string[];
        group: string;
        title: string;
        type: "string";
      };
    };
  };
  extension: ExtensionId_Type_5b6f8a91;
  family: string;
  id: string;
  isDefaultForLocation: IsDefaultForLocation_Type_b17d32ba;
  isUserSelectable: boolean;
  maxInputTokens: number;
  maxOutputTokens: number;
  modelPickerCategory: ModelPickerCategory_Type_e766cacf;
  multiplierNumeric: number;
  name: string;
  pricing: string;
  tooltip: Blob;
  vendor: string;
  version: string;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant */
export type Metadata_Variant_7403ebc8_2 = {
  auth: Auth_Type_0db0f468;
  capabilities: Capabilities_Type_024bea5e;
  configurationSchema?: {
    properties: {
      reasoningEffort: {
        default: string;
        enum: string[];
        enumDescriptions: string[];
        enumItemLabels: string[];
        group: string;
        title: string;
        type: "string";
      };
    };
  };
  extension: ExtensionId_Type_5b6f8a91;
  family: string;
  id: string;
  isDefaultForLocation: IsDefaultForLocation_Type_b17d32ba;
  isUserSelectable: boolean;
  maxInputTokens: number;
  maxOutputTokens: number;
  modelPickerCategory: ModelPickerCategory_Type_e766cacf;
  multiplier: string;
  multiplierNumeric: number;
  name: string;
  tooltip: string;
  vendor: string;
  version: string;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant */
export type Metadata_Variant_7403ebc8_3 = {
  auth: Auth_Type_0db0f468;
  capabilities: Capabilities_Type_024bea5e;
  extension: ExtensionId_Type_5b6f8a91;
  family: string;
  id: string;
  isDefaultForLocation: IsDefaultForLocation_Type_b17d32ba;
  isUserSelectable: boolean;
  maxInputTokens: number;
  maxOutputTokens: number;
  modelPickerCategory: ModelPickerCategory_Type_e766cacf;
  multiplier: string;
  multiplierNumeric: number;
  name: string;
  statusIcon: {
    id: string;
  };
  tooltip: Blob;
  vendor: string;
  version: string;
};

/** 0.v.inputState.selectedModel -> Variant.metadata -> Variant */
export type Metadata_Variant_7403ebc8_4 = {
  auth: Auth_Type_0db0f468;
  capabilities: Capabilities_Type_024bea5e;
  detail: string;
  extension: ExtensionId_Type_5b6f8a91;
  family: string;
  id: string;
  isDefaultForLocation: {
    panel: boolean;
  };
  isUserSelectable: boolean;
  maxInputTokens: number;
  maxOutputTokens: number;
  modelPickerCategory: ModelPickerCategory_Type_e766cacf;
  name: string;
  tooltip: Blob;
  vendor: string;
  version: string;
};

/** 0.v.inputState.selectedModel -> Variant */
export type SelectedModel_Type_71b7f8b2 = {
  identifier: Path;
  metadata: Metadata_Variant_7403ebc8 | Metadata_Variant_7403ebc8_2 | Metadata_Variant_7403ebc8_3 | Metadata_Variant_7403ebc8_4;
};

/** 0.v.inputState.selections[] -> Variant */
export type Range_Type_cb741af8 = {
  endColumn: number;
  endLineNumber: number;
  positionColumn: number;
  positionLineNumber: number;
  selectionStartColumn: number;
  selectionStartLineNumber: number;
  startColumn: number;
  startLineNumber: number;
};

/** 0.v.requests[] -> Variant.agent -> Variant.metadata -> Variant */
export type Metadata_Type_3e2f0323 = {
  hasFollowups: boolean;
  supportIssueReporting: boolean;
  themeIcon: {
    id: string;
  };
};

/** 0.v.requests[] -> Variant.agent -> Variant.slashCommands[] -> Variant.disambiguation[] -> Variant */
export type Disambiguation_Type_d9420919 = {
  category: string;
  description: string;
  examples: string[];
};

/** 0.v.requests[] -> Variant.agent -> Variant.slashCommands[] -> Variant */
export type SlashCommands_Variant_419759c3 = {
  description: string;
  disambiguation?: Disambiguation_Type_d9420919[];
  isSticky?: boolean;
  name: string;
  sampleRequest?: string;
};

/** 0.v.requests[] -> Variant.agent -> Variant.slashCommands[] -> Variant */
export type SlashCommands_Variant_419759c3_2 = {
  description: string;
  disambiguation?: Disambiguation_Type_d9420919[];
  name: string;
  sampleRequest: string;
  when?: string;
};

/** 0.v.requests[] -> Variant.agent -> Variant */
export type Agent_Type_dc9bd4a7 = {
  description: string;
  disambiguation: never[];
  extensionDisplayName: string;
  extensionId: ExtensionId_Type_5b6f8a91;
  extensionPublisherId: string;
  extensionVersion: Semver;
  fullName: string;
  id: string;
  isDefault: boolean;
  locations: string[];
  metadata: Metadata_Type_3e2f0323;
  modes: string[];
  name: string;
  publisherDisplayName: string;
  slashCommands: Array<SlashCommands_Variant_419759c3 | SlashCommands_Variant_419759c3_2>;
  when: string;
};

/** 0.v.requests[] -> Variant.contentReferences[] -> reference */
export type ContentReferences_Reference_b191043c = {
  kind: "reference";
  reference: $mid_1_9b4a5f71;
};

/** 0.v.requests[] -> Variant.message -> Variant.parts[].range -> Variant */
export type Range_Type_e984d3e7 = {
  endExclusive: number;
  start: number;
};

/** 0.v.requests[] -> Variant.message -> Variant */
export type Message_Type_cb5b622e = {
  parts: {
    editorRange: Range_Type_c56f3a3b;
    kind: "text";
    range: Range_Type_e984d3e7;
    text: string;
  }[];
  text: string;
};

/** 0.v.requests[] -> Variant.modelState -> Variant */
export type ModelState_Type_32b12971 = {
  completedAt?: number;
  value: number;
};

/** 0.v.requests[] -> Variant.response[] -> mcpServersStarting */
export type Response_McpServersStarting_ca747050 = {
  didStartServerIds: never[];
  kind: "mcpServersStarting";
};

/** 0.v.requests[] -> Variant.response[] -> progressTaskSerialized.content -> Variant */
export type Content_Type_c117e6d5 = {
  uris: Record<string, unknown>;
  value: string;
};

/** 0.v.requests[] -> Variant.response[] -> progressTaskSerialized */
export type Response_ProgressTaskSerialized_9e22e023 = {
  content: Content_Type_c117e6d5;
  kind: "progressTaskSerialized";
  progress: never[];
};

/** 0.v.requests[] -> Variant.response[] -> toolInvocationSerialized.invocationMessage -> Variant */
export type InvocationMessage_Variant_bfc25fae = {
  supportAlertSyntax: boolean;
  supportHtml: boolean;
  supportThemeIcons: boolean;
  uris: Record<Url, $mid_1_9b4a5f71>;
  value: string;
};

/** 0.v.requests[] -> Variant.response[] -> toolInvocationSerialized */
export type Response_ToolInvocationSerialized_4dcbc231 = {
  generatedTitle?: string;
  invocationMessage: Path | InvocationMessage_Variant_bfc25fae | string;
  isAttachedToThinking?: boolean;
  isComplete: boolean;
  isConfirmed?: {
    type: 1;
  };
  kind: "toolInvocationSerialized";
  pastTenseMessage?: InvocationMessage_Variant_bfc25fae | string;
  presentation?: string;
  resultDetails?: ResultDetails_Type_5cbf55b8[];
  source: {
    label: string;
    type: "internal";
  };
  subAgentInvocationId?: string;
  toolCallId: string;
  toolId: string;
  toolSpecificData?: {
    agentName?: string;
    description: string;
    kind: "subagent";
    modelName: string;
    prompt: Path;
    result?: string;
  };
};

/** 0.v.requests[] -> Variant.response[] -> thinking.metadata -> Variant */
export type Metadata_Variant_97f9cda1 = {
  stopReason: string;
  vscodeReasoningDone: boolean;
};

/** 0.v.requests[] -> Variant.response[] -> thinking.metadata -> Variant */
export type Metadata_Variant_97f9cda1_2 = {
  toolId: string;
};

/** 0.v.requests[] -> Variant.response[] -> thinking */
export type Response_Thinking_f3c7934d = {
  generatedTitle?: string;
  id?: string;
  kind: "thinking";
  metadata?: Metadata_Variant_97f9cda1 | Metadata_Variant_97f9cda1_2;
  value: never[] | string | Blob | Path;
};

/** 0.v.requests[] -> Variant.response[] -> Variant */
export type Response_Variant_9ed16578 = {
  baseUri?: $mid_1_9b4a5f71;
  supportAlertSyntax?: boolean;
  supportHtml: boolean;
  supportThemeIcons: boolean;
  uris?: Record<string, unknown>;
  value: string;
};

/** 0.v.requests[] -> Variant.response[] -> inlineReference.inlineReference -> 12 */
export type InlineReference_12_8b86d4f8 = {
  containerName: string;
  kind: 12;
  location: ResultDetails_Type_5cbf55b8;
  name: string;
};

/** 0.v.requests[] -> Variant.response[] -> inlineReference */
export type Response_InlineReference_19da2736 = {
  inlineReference: $mid_1_9b4a5f71 | ResultDetails_Type_5cbf55b8 | InlineReference_12_8b86d4f8;
  kind: "inlineReference";
  name?: string;
  resolveId?: Uuid;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.renderedGlobalContext[] -> 1 */
export type RenderedGlobalContext_1_70f03812 = {
  text: Path;
  type: 1;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.renderedGlobalContext[] -> 3 */
export type RenderedGlobalContext_3_f626c266 = {
  cacheType: string;
  type: 3;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.renderedUserMessage[] -> 1 */
export type RenderedUserMessage_1_e37b2dc9 = {
  text: Path;
  type: 1;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.renderedUserMessage[] -> 3 */
export type RenderedUserMessage_3_29a4bb49 = {
  cacheType: string;
  type: 3;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallResults{} -> Variant.content[] -> 21 */
export type $mid_21_db627c2b = {
  $mid: 21;
  value: string;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallResults{} -> Variant.content[] -> 23.value.node.children[] -> 1.children[] -> 2 */
export type Children_2_184155d5 = {
  lineBreakBefore: boolean;
  priority: number;
  references?: {
    anchor: $mid_1_9b4a5f71;
    options: {
      isFromTool: boolean;
    };
  }[];
  text: string;
  type: 2;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallResults{} -> Variant.content[] -> 23.value.node.children[] -> 1 */
export type Children_1_4d54983a = {
  children: Array<Children_1_4d54983a | Children_2_184155d5>;
  ctor: number;
  ctorName: string;
  props: Record<string, unknown>;
  references: never[];
  type: 1;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallResults{} -> Variant.content[] -> 23 */
export type $mid_23_16b15f28 = {
  $mid: 23;
  value: {
    node: {
      children: Array<Children_1_4d54983a | Children_2_184155d5>;
      ctor: number;
      ctorName: string;
      props: Record<string, unknown>;
      references: never[];
      type: 1;
    };
  };
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallResults{} -> Variant */
export type $mid_20_d4f9b655 = {
  $mid: 20;
  content: Array<$mid_21_db627c2b | $mid_23_16b15f28>;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallRounds[] -> Variant.thinking -> Variant */
export type Thinking_Type_c31d24a3 = {
  encrypted: Path;
  id: Base64;
  text: never[];
  tokens?: number;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallRounds[] -> Variant.toolCalls[] -> Variant */
export type ToolCalls_Type_d37e2af8 = {
  arguments: string;
  id: VscodeCallId;
  name: string;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant.toolCallRounds[] -> Variant */
export type ToolCallRounds_Type_999c9a19 = {
  id: Uuid;
  phase?: string;
  phaseModelId?: string;
  response: string;
  statefulMarker?: Path;
  thinking?: Thinking_Type_c31d24a3;
  timestamp: number;
  toolCalls: ToolCalls_Type_d37e2af8[];
  toolInputRetry: number;
};

/** 0.v.requests[] -> Variant.result -> Variant.metadata -> Variant */
export type Metadata_Type_97e20652 = {
  agentId: string;
  cacheKey?: Url;
  codeBlocks?: never[];
  modelMessageId: string;
  renderedGlobalContext?: Array<RenderedGlobalContext_1_70f03812 | RenderedGlobalContext_3_f626c266>;
  renderedUserMessage?: Array<RenderedUserMessage_1_e37b2dc9 | RenderedUserMessage_3_29a4bb49>;
  resolvedModel?: string;
  responseId: Uuid;
  sessionId: Uuid;
  toolCallResults?: Record<VscodeCallId, $mid_20_d4f9b655>;
  toolCallRounds?: ToolCallRounds_Type_999c9a19[];
};

/** 0.v.requests[] -> Variant.result -> Variant.timings -> Variant */
export type Timings_Type_bfe18f74 = {
  firstProgress?: number;
  totalElapsed: number;
};

/** 0.v.requests[] -> Variant.result -> Variant */
export type Result_Type_53c47f49 = {
  details: string;
  metadata: Metadata_Type_97e20652;
  timings: Timings_Type_bfe18f74;
};

/** 0.v.requests[] -> Variant.variableData.variables[] -> tool */
export type Variables_Tool_a642671e = {
  fullName?: string;
  icon?: {
    id: string;
  };
  id: string;
  kind: "tool";
  name: string;
  range?: Range_Type_e984d3e7;
};

/** 0.v.requests[] -> Variant.variableData.variables[] -> promptFile */
export type Variables_PromptFile_83e33e32 = {
  automaticallyAdded: boolean;
  id: Path;
  isRoot: boolean;
  kind: "promptFile";
  modelDescription: string;
  name: string;
  toolReferences?: never[];
  value: $mid_1_9b4a5f71;
};

/** 0.v.requests[] -> Variant.variableData.variables[] -> promptText */
export type Variables_PromptText_39dee4fb = {
  automaticallyAdded: boolean;
  id: string;
  kind: "promptText";
  modelDescription: string;
  name: string;
  toolReferences: {
    fullName?: string;
    icon?: {
      id: string;
    };
    id: string;
    kind: "tool";
    name: string;
    range?: Range_Type_e984d3e7;
  }[];
  value: Path;
};

/** 0.v.requests[] -> Variant.variableData.variables[] -> file */
export type Variables_File_5c76f824 = {
  id: string;
  kind: "file";
  modelDescription?: string;
  name: string;
  value: $mid_1_9b4a5f71 | ResultDetails_Type_5cbf55b8;
};

/** 0.v.requests[] -> Variant */
export type Requests_Variant_a79b3dd9 = {
  agent: Agent_Type_dc9bd4a7;
  codeCitations: never[];
  contentReferences: ContentReferences_Reference_b191043c[];
  followups?: never[];
  message: Message_Type_cb5b622e;
  modeInfo?: {
    isBuiltin: boolean;
    kind: "agent";
    modeId: string;
    modeInstructions?: {
      content: Path;
      isBuiltin: boolean;
      name: string;
      toolReferences: never[];
      uri: $mid_1_9b4a5f71;
    };
    modeName: string;
    permissionLevel: string;
  };
  modelId: Path;
  modelState: ModelState_Type_32b12971;
  requestId: string;
  response: Array<Response_McpServersStarting_ca747050 | Response_ProgressTaskSerialized_9e22e023 | Response_ToolInvocationSerialized_4dcbc231 | Response_Thinking_f3c7934d | Response_Variant_9ed16578 | Response_InlineReference_19da2736>;
  responseId: string;
  responseMarkdownInfo?: never[];
  result?: Result_Type_53c47f49;
  timeSpentWaiting: number;
  timestamp: number;
  variableData: {
    variables: Array<Variables_Tool_a642671e | Variables_PromptFile_83e33e32 | Variables_PromptText_39dee4fb | Variables_File_5c76f824>;
  };
};

/** 0.v.requests[] -> Variant.response[] -> Variant */
export type Response_Variant_9ed16578_2 = {
  baseUri: $mid_1_9b4a5f71;
  supportHtml: boolean;
  supportThemeIcons: boolean;
  value: string;
};

/** 0.v.requests[] -> Variant */
export type Requests_Variant_a79b3dd9_2 = {
  agent: Agent_Type_dc9bd4a7;
  codeCitations: never[];
  completionTokens: number;
  contentReferences: never[];
  message: Message_Type_cb5b622e;
  modeInfo: {
    isBuiltin: boolean;
    kind: "agent";
    modeId: string;
    modeInstructions?: {
      content: Path;
      isBuiltin: boolean;
      name: string;
      toolReferences: never[];
      uri: $mid_1_9b4a5f71;
    };
    modeName: string;
    permissionLevel: string;
  };
  modelId: Path;
  modelState: {
    value: number;
  };
  requestId: string;
  response: Array<Response_McpServersStarting_ca747050 | Response_ProgressTaskSerialized_9e22e023 | Response_Thinking_f3c7934d | Response_Variant_9ed16578_2 | Response_InlineReference_19da2736 | Response_ToolInvocationSerialized_4dcbc231>;
  responseId: string;
  timeSpentWaiting: number;
  timestamp: number;
  variableData: {
    variables: never[];
  };
};

/** 0 */
export type $0_801eaa31 = {
  kind: 0;
  v: {
    creationDate: number;
    customTitle?: string;
    hasPendingEdits: boolean;
    initialLocation: string;
    inputState?: {
      attachments: {
        id: string;
        kind: "file";
        modelDescription?: string;
        name: string;
        value: $mid_1_9b4a5f71 | ResultDetails_Type_5cbf55b8;
      }[];
      contrib: {
        chatDynamicVariableModel: never[];
      };
      inputText: string;
      mode: {
        id: string;
        kind: "agent";
      };
      permissionLevel?: string;
      selectedModel?: SelectedModel_Type_71b7f8b2;
      selections: Range_Type_cb741af8[];
    };
    pendingRequests?: never[];
    requests: Array<Requests_Variant_a79b3dd9 | Requests_Variant_a79b3dd9_2>;
    responderUsername: string;
    sessionId: Uuid;
    version: number;
  };
};

/** 1.v -> Variant.errorDetails -> Variant */
export type ErrorDetails_Variant_3dfcc761 = {
  code?: string;
  confirmationButtons?: {
    data: {
      copilotContinueOnError: boolean;
    };
    label: string;
  }[];
  isRateLimited?: boolean;
  level?: number;
  message: string;
  responseIsIncomplete: boolean;
};

/** 1.v -> Variant.errorDetails -> Variant */
export type ErrorDetails_Variant_3dfcc761_2 = {
  isQuotaExceeded: boolean;
  isRateLimited: boolean;
  message: string;
  responseIsIncomplete: boolean;
};

/** 1.v -> Variant.metadata -> Variant.toolCallRounds[] -> Variant */
export type ToolCallRounds_Variant_17b251ca = {
  id: Uuid;
  phase: string;
  phaseModelId: string;
  response: Blob;
  statefulMarker: Path;
  summary?: Path;
  timestamp: number;
  toolCalls: ToolCalls_Type_d37e2af8[];
  toolInputRetry: number;
};

/** 1.v -> Variant.metadata -> Variant */
export type Metadata_Variant_96fb7e68 = {
  agentId: string;
  codeBlocks: never[];
  modelMessageId: Uuid;
  renderedUserMessage: Array<RenderedUserMessage_1_e37b2dc9 | RenderedUserMessage_3_29a4bb49>;
  resolvedModel: string;
  responseId: Uuid;
  sessionId: Uuid;
  summaries: {
    contextLengthBefore?: number;
    durationMs: number;
    model: string;
    numRounds: number;
    numRoundsSinceLastSummarization: number;
    outcome?: string;
    promptTokenDetails: {
      category: string;
      label: string;
      percentageOfPrompt: number;
    }[];
    source?: string;
    summarizationMode: string;
    text: Path;
    toolCallRoundId: Uuid;
    usage: {
      completion_tokens: number;
      completion_tokens_details: {
        accepted_prediction_tokens: number;
        reasoning_tokens: number;
        rejected_prediction_tokens: number;
      };
      prompt_tokens: number;
      prompt_tokens_details: {
        cached_tokens: number;
      };
      total_tokens: number;
    };
  }[];
  toolCallResults: Record<VscodeCallId, $mid_20_d4f9b655>;
  toolCallRounds: Array<ToolCallRounds_Variant_17b251ca | ToolCallRounds_Type_999c9a19>;
};

/** 1.v -> Variant */
export type V_Variant_9dcab11c = {
  details?: string;
  errorDetails?: ErrorDetails_Variant_3dfcc761 | ErrorDetails_Variant_3dfcc761_2;
  metadata?: Metadata_Type_97e20652 | Metadata_Variant_96fb7e68;
  timings?: Timings_Type_bfe18f74;
};

/** 1.v -> agent */
export type V_Agent_2bd6bbcb = {
  id: string;
  kind: "agent";
};

/** 1.v -> Variant */
export type V_Variant_9dcab11c_2 = {
  identifier: Path;
  metadata: Metadata_Variant_7403ebc8 | Metadata_Variant_7403ebc8_2;
};

/** 1.v -> Variant */
export type V_Variant_9dcab11c_3 = {
  requestId: string;
};

/** 1.v -> Variant */
export type V_Variant_9dcab11c_4 = {
  attachments: never[];
  contrib: {
    chatDynamicVariableModel: never[];
  };
  inputText: string;
  mode: {
    id: string;
    kind: "agent";
  };
  selectedModel: {
    identifier: Path;
    metadata: {
      auth: Auth_Type_0db0f468;
      capabilities: Capabilities_Type_024bea5e;
      detail: string;
      extension: ExtensionId_Type_5b6f8a91;
      family: string;
      id: string;
      isDefaultForLocation: {
        panel: boolean;
      };
      isUserSelectable: boolean;
      maxInputTokens: number;
      maxOutputTokens: number;
      modelPickerCategory: ModelPickerCategory_Type_e766cacf;
      name: string;
      tooltip: Blob;
      vendor: string;
      version: string;
    };
  };
  selections: Range_Type_cb741af8[];
};

/** 1 */
export type $1_a2c6e3e4 = {
  k: Array<string | number>;
  kind: 1;
  v: string | Range_Type_cb741af8[] | boolean | number | V_Variant_9dcab11c | never[] | ModelState_Type_32b12971 | Blob | {
    id: string;
    kind: "file";
    modelDescription?: string;
    name: string;
    value: $mid_1_9b4a5f71 | ResultDetails_Type_5cbf55b8;
  }[] | Path | ContentReferences_Reference_b191043c[] | V_Agent_2bd6bbcb | V_Variant_9dcab11c_2 | V_Variant_9dcab11c_3 | {
    suggestionId: string;
  }[] | V_Variant_9dcab11c_4;
};

/** 2.v[] -> thinking.metadata -> Variant */
export type Metadata_Variant_e84b06b3 = {
  toolId: string;
};

/** 2.v[] -> thinking */
export type V_Thinking_0d8c201c = {
  generatedTitle?: string;
  id?: string;
  kind: "thinking";
  metadata?: Metadata_Variant_97f9cda1 | Metadata_Variant_e84b06b3;
  value: never[] | string | Blob | Path;
};

/** 2.v[] -> toolInvocationSerialized.invocationMessage -> Variant */
export type InvocationMessage_Variant_b6b5f121 = {
  isTrusted: boolean;
  supportAlertSyntax: boolean;
  supportHtml: boolean;
  supportThemeIcons: boolean;
  value: string;
};

/** 2.v[] -> toolInvocationSerialized.isConfirmed -> 1 */
export type IsConfirmed_1_5b8fc432 = {
  type: 1;
};

/** 2.v[] -> toolInvocationSerialized.isConfirmed -> 4 */
export type IsConfirmed_4_90ec962f = {
  type: 4;
};

/** 2.v[] -> toolInvocationSerialized.isConfirmed -> 0 */
export type IsConfirmed_0_9216aac8 = {
  type: 0;
};

/** 2.v[] -> toolInvocationSerialized.isConfirmed -> 5 */
export type IsConfirmed_5_a7a5bb24 = {
  type: 5;
};

/** 2.v[] -> toolInvocationSerialized.isConfirmed -> 3 */
export type IsConfirmed_3_c2d3cd7c = {
  scope: string;
  type: 3;
};

/** 2.v[] -> toolInvocationSerialized.resultDetails -> Variant */
export type ResultDetails_Variant_fbcbbe50 = {
  input: string;
  isError: boolean;
  output: {
    isText: boolean;
    type: "embed";
    value: string;
  }[];
};

/** 2.v[] -> toolInvocationSerialized.source -> internal */
export type Source_Internal_a15c9bee = {
  label: string;
  type: "internal";
};

/** 2.v[] -> toolInvocationSerialized.source -> mcp */
export type Source_Mcp_c68994a2 = {
  collectionId: Path;
  definitionId: Path;
  label: string;
  serverLabel: string;
  type: "mcp";
};

/** 2.v[] -> toolInvocationSerialized.toolSpecificData -> terminal */
export type ToolSpecificData_Terminal_8a60c52e = {
  autoApproveInfo?: {
    isTrusted: boolean;
    supportAlertSyntax: boolean;
    supportHtml: boolean;
    supportThemeIcons: boolean;
    value: string;
  };
  commandLine: {
    forDisplay?: string;
    isSandboxWrapped?: boolean;
    original: string;
    toolEdited?: string;
  };
  confirmation: {
    cdPrefix?: Path;
    commandLine: string;
    cwdLabel?: Path;
  };
  cwd: $mid_1_9b4a5f71;
  isBackground: boolean;
  kind: "terminal";
  language: string;
  requestUnsandboxedExecution?: boolean;
  requiresConfirmationForRetry?: boolean;
  terminalCommandId: string;
  terminalCommandOutput?: {
    lineCount: number;
    text: string;
  };
  terminalCommandState?: {
    duration?: number;
    exitCode?: number;
    timestamp: number;
  };
  terminalCommandUri?: $mid_1_9b4a5f71;
  terminalTheme?: {
    background: string;
    foreground: string;
  };
  terminalToolSessionId?: Uuid;
};

/** 2.v[] -> toolInvocationSerialized.toolSpecificData -> input */
export type ToolSpecificData_Input_e9170bc3 = {
  kind: "input";
  rawInput: {
    action?: string;
    directory: Path;
    files?: string[];
  };
};

/** 2.v[] -> toolInvocationSerialized.toolSpecificData -> todoList */
export type ToolSpecificData_TodoList_4e947667 = {
  kind: "todoList";
  todoList: {
    id: string;
    status: string;
    title: string;
  }[];
};

/** 2.v[] -> toolInvocationSerialized.toolSpecificData -> subagent */
export type ToolSpecificData_Subagent_d4d13177 = {
  agentName?: string;
  description: string;
  kind: "subagent";
  modelName: string;
  prompt: Path;
  result?: string;
};

/** 2.v[] -> toolInvocationSerialized */
export type V_ToolInvocationSerialized_d70cc2ca = {
  generatedTitle?: string;
  invocationMessage: InvocationMessage_Variant_bfc25fae | string | InvocationMessage_Variant_b6b5f121 | Path;
  isComplete: boolean;
  isConfirmed?: IsConfirmed_1_5b8fc432 | IsConfirmed_4_90ec962f | IsConfirmed_0_9216aac8 | IsConfirmed_5_a7a5bb24 | IsConfirmed_3_c2d3cd7c;
  kind: "toolInvocationSerialized";
  originMessage?: string;
  pastTenseMessage?: InvocationMessage_Variant_bfc25fae | InvocationMessage_Variant_b6b5f121 | string | Path;
  presentation?: string;
  resultDetails?: Array<$mid_1_9b4a5f71 | ResultDetails_Type_5cbf55b8> | ResultDetails_Variant_fbcbbe50 | ResultDetails_Type_5cbf55b8[] | never[] | $mid_1_9b4a5f71[] | Array<ResultDetails_Type_5cbf55b8 | $mid_1_9b4a5f71>;
  source: Source_Internal_a15c9bee | Source_Mcp_c68994a2;
  subAgentInvocationId?: Uuid;
  toolCallId: string;
  toolId: string;
  toolSpecificData?: ToolSpecificData_Terminal_8a60c52e | ToolSpecificData_Input_e9170bc3 | ToolSpecificData_TodoList_4e947667 | ToolSpecificData_Subagent_d4d13177;
};

/** 2.v[] -> textEditGroup.edits[][] -> Variant */
export type Edits_Type_77c82c0e = {
  range: Range_Type_c56f3a3b;
  text: string;
};

/** 2.v[] -> textEditGroup */
export type V_TextEditGroup_f858d8c6 = {
  done: boolean;
  edits: Edits_Type_77c82c0e[][];
  kind: "textEditGroup";
  state?: {
    applied: number;
    sha1: Sha1;
  };
  uri: $mid_1_9b4a5f71;
};

/** 2.v[] -> Variant.message.parts[] -> prompt */
export type Parts_Prompt_1c9a67af = {
  editorRange: Range_Type_c56f3a3b;
  kind: "prompt";
  name: string;
  range: Range_Type_e984d3e7;
};

/** 2.v[] -> Variant.message.parts[] -> text */
export type Parts_Text_31d30613 = {
  editorRange: Range_Type_c56f3a3b;
  kind: "text";
  range: Range_Type_e984d3e7;
  text: string;
};

/** 2.v[] -> Variant.response[] -> textEditGroup */
export type Response_TextEditGroup_dcef7b7f = {
  done: boolean;
  edits: Edits_Type_77c82c0e[][];
  kind: "textEditGroup";
  uri: $mid_1_9b4a5f71;
};

/** 2.v[] -> Variant.response[] -> undoStop */
export type Response_UndoStop_7197bb90 = {
  id: Uuid;
  kind: "undoStop";
};

/** 2.v[] -> Variant.response[] -> codeblockUri */
export type Response_CodeblockUri_46d3ae9d = {
  isEdit: boolean;
  kind: "codeblockUri";
  uri: $mid_1_9b4a5f71;
};

/** 2.v[] -> Variant.response[] -> questionCarousel.questions[] -> multiSelect.options[] -> Variant */
export type Options_Type_46c52020 = {
  id: string;
  label: string;
  value: string;
};

/** 2.v[] -> Variant.response[] -> questionCarousel.questions[] -> multiSelect */
export type Questions_MultiSelect_269537bd = {
  allowFreeformInput: boolean;
  defaultValue: string[];
  id: Uuid;
  message: string;
  options: Options_Type_46c52020[];
  title: string;
  type: "multiSelect";
};

/** 2.v[] -> Variant.response[] -> questionCarousel.questions[] -> text */
export type Questions_Text_98edc065 = {
  allowFreeformInput: boolean;
  id: Uuid;
  message: Blob;
  title: string;
  type: "text";
};

/** 2.v[] -> Variant.response[] -> questionCarousel.questions[] -> singleSelect */
export type Questions_SingleSelect_524a89e6 = {
  allowFreeformInput: boolean;
  defaultValue?: string;
  id: Uuid;
  message: string;
  options: Options_Type_46c52020[];
  title: string;
  type: "singleSelect";
};

/** 2.v[] -> Variant.response[] -> questionCarousel */
export type Response_QuestionCarousel_64466816 = {
  allowSkip: boolean;
  data?: Record<Uuid, string>;
  isUsed?: boolean;
  kind: "questionCarousel";
  questions: Array<Questions_MultiSelect_269537bd | Questions_Text_98edc065 | Questions_SingleSelect_524a89e6>;
  resolveId: Uuid;
};

/** 2.v[] -> Variant */
export type V_Variant_ca258acf = {
  agent: Agent_Type_dc9bd4a7;
  codeCitations: never[];
  completionTokens?: number;
  contentReferences: ContentReferences_Reference_b191043c[];
  editedFileEvents?: {
    eventKind: number;
    uri: $mid_1_9b4a5f71;
  }[];
  elapsedMs?: number;
  followups?: never[];
  isSystemInitiated?: boolean;
  message: {
    parts: Array<Parts_Prompt_1c9a67af | Parts_Text_31d30613>;
    text: string;
  };
  modeInfo?: {
    isBuiltin: boolean;
    kind: "agent";
    modeId: string;
    modeInstructions?: {
      content: Path;
      isBuiltin: boolean;
      name: string;
      toolReferences: never[];
      uri: $mid_1_9b4a5f71;
    };
    modeName: string;
    permissionLevel: string;
  };
  modelId: Path;
  modelState: ModelState_Type_32b12971;
  requestId: string;
  response: Array<Response_McpServersStarting_ca747050 | Response_ProgressTaskSerialized_9e22e023 | Response_Thinking_f3c7934d | Response_ToolInvocationSerialized_4dcbc231 | Response_TextEditGroup_dcef7b7f | Response_Variant_9ed16578 | Response_InlineReference_19da2736 | Response_UndoStop_7197bb90 | Response_CodeblockUri_46d3ae9d | Response_QuestionCarousel_64466816>;
  responseId: string;
  responseMarkdownInfo?: never[];
  result?: {
    details: string;
    metadata: Metadata_Type_97e20652;
    timings: Timings_Type_bfe18f74;
  };
  systemInitiatedLabel?: Path;
  terminalExecutionId?: Uuid;
  timeSpentWaiting: number;
  timestamp: number;
  variableData: {
    variables: Array<Variables_File_5c76f824 | Variables_PromptFile_83e33e32 | Variables_PromptText_39dee4fb | Variables_Tool_a642671e>;
  };
};

/** 2.v[] -> steering */
export type V_Steering_8d80ed08 = {
  id: string;
  kind: "steering";
  request: {
    isSystemInitiated: boolean;
    message: Message_Type_cb5b622e;
    modeInfo: {
      isBuiltin: boolean;
      kind: "agent";
      modeId: string;
      modeInstructions?: {
        content: Path;
        isBuiltin: boolean;
        name: string;
        toolReferences: never[];
        uri: $mid_1_9b4a5f71;
      };
      modeName: string;
      permissionLevel: string;
    };
    modelId: Path;
    requestId: string;
    systemInitiatedLabel: Path;
    terminalExecutionId: Uuid;
    timestamp: number;
    variableData: {
      variables: never[];
    };
  };
  sendOptions: {
    isSystemInitiated: boolean;
    modeInfo: {
      isBuiltin: boolean;
      kind: "agent";
      modeId: string;
      modeInstructions?: {
        content: Path;
        isBuiltin: boolean;
        name: string;
        toolReferences: never[];
        uri: $mid_1_9b4a5f71;
      };
      modeName: string;
      permissionLevel: string;
    };
    systemInitiatedLabel: Path;
    terminalExecutionId: Uuid;
    userSelectedModelId: Path;
    userSelectedTools: Record<string, boolean>;
  };
};

/** 2.v[] -> inlineReference */
export type V_InlineReference_3f1ce092 = {
  inlineReference: $mid_1_9b4a5f71 | InlineReference_12_8b86d4f8 | ResultDetails_Type_5cbf55b8;
  kind: "inlineReference";
  name?: string;
  resolveId?: Uuid;
};

/** 2.v[] -> undoStop */
export type V_UndoStop_d2a847c5 = {
  id: Uuid;
  kind: "undoStop";
};

/** 2.v[] -> codeblockUri */
export type V_CodeblockUri_d78e5a97 = {
  isEdit: boolean;
  kind: "codeblockUri";
  subAgentInvocationId?: Uuid;
  uri: $mid_1_9b4a5f71;
};

/** 2.v[] -> progressTaskSerialized */
export type V_ProgressTaskSerialized_e9b9bdfc = {
  content: Content_Type_c117e6d5 | InvocationMessage_Variant_b6b5f121;
  kind: "progressTaskSerialized";
  progress: never[];
};

/** 2.v[] -> questionCarousel.data{} -> Variant */
export type Data_Variant_d01ee24c = {
  freeformValue?: string;
  selectedValues: string[];
};

/** 2.v[] -> questionCarousel.data{} -> Variant */
export type Data_Variant_d01ee24c_2 = {
  freeformValue: string;
};

/** 2.v[] -> questionCarousel.data{} -> Variant */
export type Data_Variant_d01ee24c_3 = {
  selectedValue: string;
};

/** 2.v[] -> questionCarousel */
export type V_QuestionCarousel_9c81803f = {
  allowSkip: boolean;
  data?: Record<Uuid, string | Data_Variant_d01ee24c | Data_Variant_d01ee24c_2 | Data_Variant_d01ee24c_3>;
  isUsed?: boolean;
  kind: "questionCarousel";
  questions: Array<Questions_Text_98edc065 | Questions_MultiSelect_269537bd | Questions_SingleSelect_524a89e6>;
  resolveId: Uuid;
};

/** 2.v[] -> Variant.message.parts[] -> agent */
export type Parts_Agent_267d30fc = {
  agent: Agent_Type_dc9bd4a7;
  editorRange: Range_Type_c56f3a3b;
  kind: "agent";
  range: Range_Type_e984d3e7;
};

/** 2.v[] -> Variant */
export type V_Variant_ca258acf_2 = {
  agent: Agent_Type_dc9bd4a7;
  codeCitations: never[];
  confirmation: string;
  contentReferences: never[];
  followups: never[];
  message: {
    parts: Array<Parts_Agent_267d30fc | Parts_Text_31d30613>;
    text: string;
  };
  modeInfo: {
    isBuiltin: boolean;
    kind: "agent";
    modeId: string;
    modeInstructions?: {
      content: Path;
      isBuiltin: boolean;
      name: string;
      toolReferences: never[];
      uri: $mid_1_9b4a5f71;
    };
    modeName: string;
    permissionLevel: string;
  };
  modelId: Path;
  modelState: ModelState_Type_32b12971;
  requestId: string;
  response: Array<Response_McpServersStarting_ca747050 | Response_Variant_9ed16578_2>;
  responseId: string;
  responseMarkdownInfo: never[];
  result: {
    details: string;
    metadata: {
      agentId: string;
      codeBlocks: never[];
      modelMessageId: Uuid;
      resolvedModel: string;
      responseId: Uuid;
      sessionId: Uuid;
      toolCallRounds: {
        id: Uuid;
        response: Path;
        timestamp: number;
        toolCalls: never[];
        toolInputRetry: number;
      }[];
    };
    timings: Timings_Type_bfe18f74;
  };
  timeSpentWaiting: number;
  timestamp: number;
  variableData: {
    variables: never[];
  };
};

/** 2.v[] -> workspaceEdit */
export type V_WorkspaceEdit_a6e76e67 = {
  edits: {
    oldResource: $mid_1_9b4a5f71;
  }[];
  kind: "workspaceEdit";
};

/** 2.v[] -> elicitationSerialized */
export type V_ElicitationSerialized_44716c0f = {
  isHidden: boolean;
  kind: "elicitationSerialized";
  message: {
    isTrusted: boolean;
    supportAlertSyntax: boolean;
    supportHtml: boolean;
    supportThemeIcons: boolean;
    value: string;
  };
  state: string;
  subtitle: string;
  title: {
    isTrusted: boolean;
    supportAlertSyntax: boolean;
    supportHtml: boolean;
    supportThemeIcons: boolean;
    value: string;
  };
};

/** 2 */
export type $2_3da03859 = {
  i?: number;
  k: Array<string | number>;
  kind: 2;
  v?: Array<V_Thinking_0d8c201c | Response_Variant_9ed16578 | V_ToolInvocationSerialized_d70cc2ca | V_TextEditGroup_f858d8c6 | V_Variant_ca258acf | V_Steering_8d80ed08 | V_InlineReference_3f1ce092 | V_UndoStop_d2a847c5 | V_CodeblockUri_d78e5a97 | V_ProgressTaskSerialized_e9b9bdfc | V_QuestionCarousel_9c81803f | V_Variant_ca258acf_2 | V_WorkspaceEdit_a6e76e67 | V_ElicitationSerialized_44716c0f | InvocationMessage_Variant_b6b5f121>;
};

export type CopilotChat = $0_801eaa31 | $1_a2c6e3e4 | $2_3da03859;
